from pydantic import computed_field
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    DATABASE_URL: str = "sqlite:///./mat_planner.db"
    API_HOST: str = "0.0.0.0"
    API_PORT: int = 8000
    LOG_LEVEL: str = "INFO"
    # LLM
    LLM_API_KEY: str = ""
    LLM_BASE_URL: str = ""
    LLM_MODEL: str = ""
    # Embedding (向量检索)
    EMBED_MODEL: str = "BAAI/bge-m3"
    EMBED_ENABLED: bool = True
    EMBED_BATCH_SIZE: int = 32   # chunks per API call
    EMBED_DIM: int = 1024        # bge-m3 output dimension
    # LLM-assisted NER
    LLM_NER_ENABLED: bool = True
    # Query expansion (synonym expansion before keyword search)
    QUERY_EXPANSION_ENABLED: bool = True
    # LLM-based reranker (score top candidates after RRF)
    RERANK_ENABLED: bool = True
    RERANK_TOP_K: int = 20   # candidates to score; final result is top_k
    # ReAct multi-hop (agent can loop for additional tool calls)
    MULTIHOP_ENABLED: bool = True
    MULTIHOP_MAX_ROUNDS: int = 2
    # Subproblem decomposition (parallel tool execution for complex queries)
    DECOMPOSITION_ENABLED: bool = True
    DECOMPOSITION_MAX_WORKERS: int = 4   # parallel threads for sub-problem execution
    # Answer self-verification (Reflection node after Answer Builder)
    REFLECTION_ENABLED: bool = True
    # Document tree BFS expansion (sibling/parent section context after retrieval)
    TREE_EXPANSION_ENABLED: bool = True
    TREE_EXPANSION_MAX_SECTIONS: int = 3   # max extra sections to pull in
    # Session memory compression (rolling summary after N messages)
    SESSION_COMPRESSION_THRESHOLD: int = 12  # messages (= 6 exchanges)
    # Knowledge graph retrieval expansion (graph-guided neighbor context)
    GRAPH_EXPANSION_ENABLED: bool = True
    GRAPH_EXPANSION_MAX_ENTITIES: int = 3   # max neighbor entities to expand per query
    GRAPH_EXPANSION_MIN_WEIGHT: float = 0.3 # min edge weight to follow
    # HyDE: Hypothetical Document Embeddings (improves semantic recall for technical queries)
    # A brief hypothetical passage is generated by the LLM and its embedding is averaged
    # with the raw query embedding before vector search.
    HYDE_ENABLED: bool = True
    HYDE_MAX_TOKENS: int = 120   # hypothetical passage length in tokens
    # VLM figure/table captioning (requires a multimodal model)
    VLM_ENABLED: bool = False    # set True when a VLM is available
    VLM_MODEL: str = ""          # e.g. "deepseek-vl2", "qwen-vl-plus", "gpt-4o"
    VLM_MIN_IMAGE_BYTES: int = 4096   # skip tiny icons below this size
    # Chunk & section memory: LLM-generated summaries + keywords during ingestion
    # Summaries are stored on parent chunks and DocumentSection rows, powering agentic navigation.
    CHUNK_SUMMARY_ENABLED: bool = True
    CHUNK_SUMMARY_MAX_TOKENS: int = 80   # target summary length in tokens
    # Agentic retrieval: LLM navigates the section tree before fetching content
    # More accurate than flat retrieval for complex / multi-section queries.
    AGENTIC_RETRIEVAL_ENABLED: bool = True
    AGENTIC_MAX_DOCS: int = 3            # candidate documents to navigate
    AGENTIC_MAX_NAV_STEPS: int = 6       # max navigation steps per document
    AGENTIC_PLANNING_TOKENS: int = 3000  # token budget for all nav LLM calls
    AGENTIC_CONTEXT_TOKENS: int = 5000   # token budget for final evidence text

    model_config = SettingsConfigDict(env_file=".env", extra="ignore")

    @computed_field
    @property
    def is_postgres(self) -> bool:
        """True when DATABASE_URL points to PostgreSQL (enables pgvector path)."""
        return self.DATABASE_URL.startswith("postgresql")


settings = Settings()
